version: "3"
services:
  web-main:
    build:
      context: .
      dockerfile: ./Docker/main_app/Dockerfile
    ports: [ "8080:8880" ]
    volumes: [ ./thunder_delivery:/thunder_delivery ]
    environment:
        FLASK_ENV: development
        LOGIN_JWT_SECRET: $LOGIN_JWT_SECRET
        SECRET_KEY: $SECRET_KEY
  web-db:
    build:
      context: .
      dockerfile: ./Docker/db_app/Dockerfile
    ports: [ "8081:8881" ]
    volumes: [ ./thunder_delivery:/thunder_delivery ]
    environment:
        FLASK_ENV: development
        LOGIN_JWT_SECRET: $LOGIN_JWT_SECRET
  redis-db:
    image: "redis:alpine"
  web-courier:
    build:
      context: .
      dockerfile: ./Docker/courier_app/Dockerfile
    ports: [ "8082:8882" ]
    volumes: [ ./thunder_delivery:/thunder_delivery ]
    environment:
        FLASK_ENV: development
        LOGIN_JWT_SECRET: $LOGIN_JWT_SECRET
        SECRET_KEY: $SECRET_KEY
  web-locker:
    build:
      context: .
      dockerfile: ./Docker/locker_app/Dockerfile
    ports: [ "8083:8883" ]
    volumes: [ ./thunder_delivery:/thunder_delivery ]
    environment:
        FLASK_ENV: development
        LOGIN_JWT_SECRET: $LOGIN_JWT_SECRET
  web-socket:
    build:
      context: .
      dockerfile: ./Docker/socket_manager/Dockerfile
    ports: [ "8084:8884" ]
    volumes: [ ./thunder_delivery:/thunder_delivery ]